# fly.toml app configuration file generated for 1comp7940lab56 on 2025-03-20T23:13:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '1comp7940lab56'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ["paketo-buildpacks/python"]

[env]
  PORT = '8080'
  PATH = "/home/vcap/deps/0/python/bin:$PATH"

[[services]]
  internal_port = 8000
  protocol = "tcp"

[services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[vm]]
  size = 'shared-cpu-1x'
